apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: mywebsite-os1
  metadata:
  annotations:
    argocd/app-name: mywebsite-os1
    backstage.io/adr-location: docs/adr
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: mywebsite-os1
    backstage.io/kubernetes-namespace: mywebsite-os1
    github.com/project-slug: neenspa/mywebsite-os1
    janus-idp.io/tekton-enabled: 'true'
  links:
    - url: https://console-openshift-console.apps.democp.vega.local/pipelines/ns/mywebsite-os1/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.democp.vega.local/k8s/ns/saturday-test-k8s/deployments/mywebsite-os1
      title: Deployment
      icon: web
    - url: https://devspaces.apps.democp.vega.local/#https://github.com/neenspa/mywebsite-os1?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: website
  owner: user:guest
  lifecycle: production
